/**
 * Production Server Template
 *
 * This module generates the server.js file for production.
 * Auto-generated by vue-easy-ssr build command.
 */

export function getServerTemplate(): string {
  return `
import express from 'express';
import { readFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const clientDir = resolve(__dirname, '../client');
const isProd = process.env.NODE_ENV === 'production';

// Import render function
const { render } = await import('./entry.js');

// Read manifest for preload links
let manifest = {};
const manifestPath = resolve(clientDir, '.vite/manifest.json');
if (existsSync(manifestPath)) {
  manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'));
}

// Read HTML template
const template = readFileSync(resolve(clientDir, 'index.html'), 'utf-8');

const app = express();

// Serve static files
app.use(express.static(clientDir, {
  index: false,
  maxAge: isProd ? '1y' : 0,
}));

// Handle all routes with SSR
app.get('*', async (req, res) => {
  try {
    const html = await render(req.originalUrl, manifest, template);
    res.status(200).set({ 'Content-Type': 'text/html' }).send(html);
  } catch (error) {
    console.error('[vue-easy-ssr] SSR Error:', error);
    res.status(500).send('Internal Server Error');
  }
});

const port = process.env.PORT || 3000;

app.listen(port, () => {
  console.log(\`
  🚀 Vue Easy SSR Server running at http://localhost:\${port}

  Mode: \${isProd ? '📦 Production' : '🔧 Development'}
  \`);
});
`.trim();
}

/**
 * Generate package.json for dist/server
 */
export function getServerPackageJson(): string {
  return JSON.stringify(
    {
      name: "vue-easy-ssr-server",
      type: "module",
      scripts: {
        start: "node server.js",
      },
      dependencies: {
        express: "^4.21.0",
      },
    },
    null,
    2
  );
}
